"__nw__FUI" = 0x801cc8bc;
"__dl__FPv" = 0x801cc8c0;
"__start_RTDL" = 0x80006310;
"AbsF32__Q33hel4math4MathFf" = 0x80387a58;
"vc_mutableArr_enemy" = 0x803773C4;
"location__Q43scn4step5enemy5EnemyCFv" = 0x80375e8c;
"location__Q43scn4step4hero4HeroCFv" = 0x804eda9c;

"enemyManager__Q33scn4step9ComponentFv" = 0x8023f330;
"heroManager__Q33scn4step9ComponentFv" = 0x8023f2f4;
"CreateDefault__Q33scn4step17ContextHeroIndiviFv" = 0x8023f8a0;
"createHeroAndStart__Q43scn4step4hero7ManagerFUlRCQ33hel4math7Vector2RCQ33hel4math7Vector2bRCQ33scn4step17ContextHeroIndiviQ43scn4step4hero10StepInKind" = 0x804f52ec;

"isMainPlayer__Q43scn4step4hero4HeroCFv" = 0x804ebafc;
"setChild__Q43scn4step4hero9PiggybackFRQ43scn4step4hero9Piggyback" = 0x80505858;
"hitStop__Q43scn4step4hero4HeroFv" = 0x804edafc;

"infoManager__Q33scn4step9ComponentFv" = 0x8023ef18;
"enemyCtrl__Q53scn4step4boss14mahoroabattle26CustomFv" = 0x802f23e4;
"heroPanel__Q43scn4step4info14InfoGameStatusFUl" = 0x805cfbb8;
"SetupInfo__Q43scn4step4hero7UtilityFRQ43scn4step4info9HeroPanelQ43scn4step4hero4KindQ43scn4step4hero11AbilityKindbbb" = 0x8050f97c;
"mutableArray_InactiveHero" = 0x804f4c0c;

"setText__Q23lyt12PaneAccessorCFPCw" = 0x801b9b04;
